// Copyright 2026 OrgMentem. Licensed under MIT. See LICENSE.
// Deterministic reference-doc generator for the papio documentation site. It
// walks the live cobra command tree and emits docs/reference/commands.md. That
// page is code-generated and drift-gated in CI (see .github/workflows/ci.yml
// docs-drift job) so it cannot fall out of sync with the binary. Regenerate
// with `make docs-gen`.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/spf13/cobra"
	"github.com/spf13/pflag"

	"papio/internal/cli"
)

const genHeader = "<!-- Code-generated by cmd/docs-gen; DO NOT EDIT. Regenerate with `make docs-gen`. -->\n"

func main() {
	outDir := flag.String("out", filepath.Join("docs", "reference"), "output directory for generated reference pages")
	flag.Parse()

	if err := run(*outDir); err != nil {
		fmt.Fprintln(os.Stderr, "docs-gen:", err)
		os.Exit(1)
	}
}

func run(outDir string) error {
	if err := os.MkdirAll(outDir, 0o755); err != nil {
		return err
	}
	root := cli.NewRoot(io.Discard, io.Discard)
	body := renderCommands(root)
	path := filepath.Join(outDir, "commands.md")
	if err := os.WriteFile(path, body, 0o600); err != nil {
		return err
	}
	fmt.Println("wrote", path)
	return nil
}

// ---- command reference ----------------------------------------------------

func renderCommands(root *cobra.Command) []byte {
	var b bytes.Buffer
	b.WriteString(genHeader)
	b.WriteString("# Command reference\n\n")
	b.WriteString("Every `papio` command, generated directly from the binary. Pass `--json` to any command for structured output; see the [user guide](../guide/user-guide.md) for the operational workflow and the [configuration reference](config-reference.md) for policy.\n\n")

	if gf := flagRows(root.PersistentFlags()); len(gf) > 0 {
		b.WriteString("## Global flags\n\n")
		b.WriteString("These flags are available on every command.\n\n")
		writeFlagTable(&b, gf)
		b.WriteString("\n")
	}

	for _, c := range visibleSubcommands(root) {
		writeCommand(&b, c, 2)
	}
	return b.Bytes()
}

func writeCommand(b *bytes.Buffer, c *cobra.Command, level int) {
	hashes := strings.Repeat("#", level)
	fmt.Fprintf(b, "%s `%s`\n\n", hashes, c.CommandPath())

	if s := strings.TrimSpace(c.Short); s != "" {
		fmt.Fprintf(b, "%s\n\n", s)
	}
	if long := strings.TrimSpace(c.Long); long != "" && long != strings.TrimSpace(c.Short) {
		fmt.Fprintf(b, "%s\n\n", long)
	}

	fmt.Fprintf(b, "```\n%s\n```\n\n", strings.TrimSpace(c.UseLine()))

	if ex := strings.TrimSpace(c.Example); ex != "" {
		b.WriteString("Examples:\n\n")
		fmt.Fprintf(b, "```bash\n%s\n```\n\n", ex)
	}

	if rows := flagRows(c.NonInheritedFlags()); len(rows) > 0 {
		writeFlagTable(b, rows)
		b.WriteString("\n")
	}

	for _, sub := range visibleSubcommands(c) {
		writeCommand(b, sub, min(level+1, 6))
	}
}

func visibleSubcommands(c *cobra.Command) []*cobra.Command {
	var out []*cobra.Command
	for _, sub := range c.Commands() {
		if sub.Hidden || !sub.IsAvailableCommand() {
			continue
		}
		switch sub.Name() {
		case "help", "completion":
			continue
		}
		out = append(out, sub)
	}
	sort.Slice(out, func(i, j int) bool { return out[i].Name() < out[j].Name() })
	return out
}

type flagRow struct{ name, typ, def, usage string }

func flagRows(fs *pflag.FlagSet) []flagRow {
	var rows []flagRow
	fs.VisitAll(func(f *pflag.Flag) {
		if f.Hidden {
			return
		}
		name := "--" + f.Name
		if f.Shorthand != "" {
			name = "-" + f.Shorthand + ", " + name
		}
		rows = append(rows, flagRow{
			name:  name,
			typ:   f.Value.Type(),
			def:   f.DefValue,
			usage: strings.ReplaceAll(f.Usage, "|", "\\|"),
		})
	})
	sort.Slice(rows, func(i, j int) bool { return rows[i].name < rows[j].name })
	return rows
}

func writeFlagTable(b *bytes.Buffer, rows []flagRow) {
	b.WriteString("| Flag | Type | Default | Description |\n")
	b.WriteString("| --- | --- | --- | --- |\n")
	for _, r := range rows {
		def := r.def
		if def != "" {
			def = "`" + def + "`"
		}
		fmt.Fprintf(b, "| `%s` | `%s` | %s | %s |\n", r.name, r.typ, def, r.usage)
	}
}
