// Copyright 2026 OrgMentem. Licensed under MIT. See LICENSE.
// Deterministic reference-doc generator for the papio documentation site. It
// walks the live cobra command tree and emits docs/reference/commands.md. That
// page is code-generated and drift-gated in CI (see .github/workflows/ci.yml
// docs-drift job) so it cannot fall out of sync with the binary. Regenerate
// with `make docs-gen`.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"

	"github.com/spf13/cobra"
	"github.com/spf13/pflag"
	"gopkg.in/yaml.v2"

	"papio/internal/cli"
)

const genHeader = "<!-- Code-generated by cmd/docs-gen; DO NOT EDIT. Regenerate with `make docs-gen`. -->\n"

func main() {
	outDir := flag.String("out", filepath.Join("docs", "reference"), "output directory for generated reference pages")
	// -llms-out generates agent-facing llms.txt +
	// llms-full.txt into the given dir (the built site) and skips reference
	// regen. Emitted at deploy time (see docs.yml), never committed, so they
	// cannot drift — same lifecycle as the live badge.
	llmsOut := flag.String("llms-out", "", "generate llms.txt + llms-full.txt into this dir (skips reference generation)")
	flag.Parse()

	if *llmsOut != "" {
		if err := generateLLMS("docs", "mkdocs.yml", *llmsOut); err != nil {
			fmt.Fprintln(os.Stderr, "docs-gen:", err)
			os.Exit(1)
		}
		return
	}

	if err := run(*outDir); err != nil {
		fmt.Fprintln(os.Stderr, "docs-gen:", err)
		os.Exit(1)
	}
}

func run(outDir string) error {
	if err := os.MkdirAll(outDir, 0o755); err != nil {
		return err
	}
	root := cli.NewRoot(io.Discard, io.Discard)
	body := renderCommands(root)
	path := filepath.Join(outDir, "commands.md")
	if err := os.WriteFile(path, body, 0o600); err != nil {
		return err
	}
	fmt.Println("wrote", path)
	return nil
}

// ---- command reference ----------------------------------------------------

func renderCommands(root *cobra.Command) []byte {
	var b bytes.Buffer
	b.WriteString(genHeader)
	b.WriteString("# Command reference\n\n")
	b.WriteString("Every `papio` command, generated directly from the binary. Pass `--json` to any command for structured output; see the [user guide](../guide/user-guide.md) for the operational workflow and the [configuration reference](config-reference.md) for policy.\n\n")

	if gf := flagRows(root.PersistentFlags()); len(gf) > 0 {
		b.WriteString("## Global flags\n\n")
		b.WriteString("These flags are available on every command.\n\n")
		writeFlagTable(&b, gf)
		b.WriteString("\n")
	}

	for _, c := range visibleSubcommands(root) {
		writeCommand(&b, c, 2)
	}
	return b.Bytes()
}

func writeCommand(b *bytes.Buffer, c *cobra.Command, level int) {
	hashes := strings.Repeat("#", level)
	fmt.Fprintf(b, "%s `%s`\n\n", hashes, c.CommandPath())

	if s := strings.TrimSpace(c.Short); s != "" {
		fmt.Fprintf(b, "%s\n\n", s)
	}
	if long := strings.TrimSpace(c.Long); long != "" && long != strings.TrimSpace(c.Short) {
		fmt.Fprintf(b, "%s\n\n", long)
	}

	fmt.Fprintf(b, "```\n%s\n```\n\n", strings.TrimSpace(c.UseLine()))

	if ex := strings.TrimSpace(c.Example); ex != "" {
		b.WriteString("Examples:\n\n")
		fmt.Fprintf(b, "```bash\n%s\n```\n\n", ex)
	}

	if rows := flagRows(c.NonInheritedFlags()); len(rows) > 0 {
		writeFlagTable(b, rows)
		b.WriteString("\n")
	}

	for _, sub := range visibleSubcommands(c) {
		writeCommand(b, sub, min(level+1, 6))
	}
}

func visibleSubcommands(c *cobra.Command) []*cobra.Command {
	var out []*cobra.Command
	for _, sub := range c.Commands() {
		if sub.Hidden || !sub.IsAvailableCommand() {
			continue
		}
		switch sub.Name() {
		case "help", "completion":
			continue
		}
		out = append(out, sub)
	}
	sort.Slice(out, func(i, j int) bool { return out[i].Name() < out[j].Name() })
	return out
}

type flagRow struct{ name, typ, def, usage string }

func flagRows(fs *pflag.FlagSet) []flagRow {
	var rows []flagRow
	fs.VisitAll(func(f *pflag.Flag) {
		if f.Hidden {
			return
		}
		name := "--" + f.Name
		if f.Shorthand != "" {
			name = "-" + f.Shorthand + ", " + name
		}
		rows = append(rows, flagRow{
			name:  name,
			typ:   f.Value.Type(),
			def:   f.DefValue,
			usage: strings.ReplaceAll(f.Usage, "|", "\\|"),
		})
	})
	sort.Slice(rows, func(i, j int) bool { return rows[i].name < rows[j].name })
	return rows
}

func writeFlagTable(b *bytes.Buffer, rows []flagRow) {
	b.WriteString("| Flag | Type | Default | Description |\n")
	b.WriteString("| --- | --- | --- | --- |\n")
	for _, r := range rows {
		def := r.def
		if def != "" {
			def = "`" + def + "`"
		}
		fmt.Fprintf(b, "| `%s` | `%s` | %s | %s |\n", r.name, r.typ, def, r.usage)
	}
}

// ---- agent-facing llms.txt / llms-full.txt --------------------------------
// The docs site serves only HTML, which is poor input for agents. We emit two
// artifacts at the site root: llms.txt (a concise, navigable index) and
// llms-full.txt (the complete docs as Markdown). Generated at deploy time from
// the same Markdown sources, so they never drift.

const llmsSiteURL = "https://orgmentem.github.io/papio/"

var llmsCommentRE = regexp.MustCompile(`(?s)<!--.*?-->\n?`)

type llmsPage struct {
	rel     string
	url     string
	section string
	title   string
	desc    string
	body    string // cleaned Markdown
}

type llmsNavPage struct {
	rel     string
	section string
}

func generateLLMS(srcDir, navPath, outDir string) error {
	var paths []string
	err := filepath.WalkDir(srcDir, func(p string, d os.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if !d.IsDir() && strings.HasSuffix(p, ".md") {
			paths = append(paths, p)
		}
		return nil
	})
	if err != nil {
		return err
	}

	byRel := make(map[string]llmsPage, len(paths))
	for _, p := range paths {
		raw, err := os.ReadFile(p)
		if err != nil {
			return err
		}
		body := strings.TrimSpace(llmsCommentRE.ReplaceAllString(string(raw), ""))
		rel := strings.TrimSuffix(strings.TrimPrefix(filepath.ToSlash(p), filepath.ToSlash(srcDir)+"/"), ".md")
		url := llmsSiteURL
		if rel != "index" {
			url += rel + "/"
		}
		byRel[rel] = llmsPage{
			rel:   rel,
			url:   url,
			title: llmsTitle(body, rel),
			desc:  llmsDesc(body),
			body:  body,
		}
	}

	navPages, err := readLLMSNav(navPath)
	if err != nil {
		return err
	}
	pages := make([]llmsPage, 0, len(navPages))
	for _, navPage := range navPages {
		page, ok := byRel[navPage.rel]
		if !ok {
			return fmt.Errorf("nav page %q does not exist under %s", navPage.rel+".md", srcDir)
		}
		page.section = navPage.section
		pages = append(pages, page)
	}

	if err := os.MkdirAll(outDir, 0o755); err != nil {
		return err
	}
	if err := os.WriteFile(filepath.Join(outDir, "llms.txt"), []byte(renderLLMSIndex(pages)), 0o600); err != nil {
		return err
	}
	if err := os.WriteFile(filepath.Join(outDir, "llms-full.txt"), []byte(renderLLMSFull(pages)), 0o600); err != nil {
		return err
	}
	fmt.Println("wrote", filepath.Join(outDir, "llms.txt"), "and llms-full.txt")
	return nil
}

func readLLMSNav(path string) ([]llmsNavPage, error) {
	raw, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	var config struct {
		Nav []yaml.MapSlice `yaml:"nav"`
	}
	if err := yaml.Unmarshal(raw, &config); err != nil {
		return nil, err
	}

	var pages []llmsNavPage
	for _, entry := range config.Nav {
		for _, item := range entry {
			section, ok := item.Key.(string)
			if !ok {
				return nil, fmt.Errorf("invalid nav section %v", item.Key)
			}
			if page, ok := item.Value.(string); ok {
				pages = append(pages, llmsNavPage{rel: strings.TrimSuffix(page, ".md"), section: llmsSection(section, page)})
				continue
			}
			children, ok := item.Value.([]interface{})
			if !ok {
				return nil, fmt.Errorf("invalid nav section %q", section)
			}
			for _, child := range children {
				for _, childItem := range llmsMapItems(child) {
					page, ok := childItem.Value.(string)
					if !ok {
						return nil, fmt.Errorf("invalid nav page in section %q", section)
					}
					pages = append(pages, llmsNavPage{rel: strings.TrimSuffix(page, ".md"), section: section})
				}
			}
		}
	}
	return pages, nil
}

func llmsMapItems(v interface{}) yaml.MapSlice {
	switch v := v.(type) {
	case yaml.MapSlice:
		return v
	case map[interface{}]interface{}:
		items := make(yaml.MapSlice, 0, len(v))
		for key, value := range v {
			items = append(items, yaml.MapItem{Key: key, Value: value})
		}
		return items
	default:
		return nil
	}
}

func llmsSection(navTitle, path string) string {
	if path == "index.md" {
		return "Overview"
	}
	return navTitle
}

func llmsTitle(body, rel string) string {
	for _, line := range strings.Split(body, "\n") {
		if strings.HasPrefix(line, "# ") {
			return strings.TrimSpace(line[2:])
		}
	}
	return rel
}

func llmsDesc(body string) string {
	var paragraph []string
	for _, line := range strings.Split(body, "\n") {
		t := strings.TrimSpace(line)
		if len(paragraph) == 0 {
			if t == "" || strings.HasPrefix(t, "#") || strings.HasPrefix(t, "<") || strings.HasPrefix(t, "!") {
				continue
			}
			paragraph = append(paragraph, t)
			continue
		}
		if t == "" {
			break
		}
		paragraph = append(paragraph, t)
	}
	if len(paragraph) == 0 {
		return ""
	}
	desc := strings.NewReplacer("**", "", "`", "").Replace(strings.Join(paragraph, " "))
	return desc
}

func renderLLMSIndex(pages []llmsPage) string {
	var b strings.Builder
	b.WriteString("# papio\n\n")
	b.WriteString("> A local paper-acquisition broker — searches scholarly works, creates acquisition jobs, validates candidate PDFs, and hands ready artifacts to Zotero through zotio.\n\n")
	b.WriteString("For AI agents: papio is a local paper-acquisition broker. Fastest path:\n")
	b.WriteString("1. Install: build `./cmd/papio` (see [Getting started](" + llmsSiteURL + "guide/getting-started/)); install Poppler and Tesseract for PDF validation.\n")
	b.WriteString("2. Initialize the local profile with `papio init`.\n")
	b.WriteString("3. For MCP hosts, run `papio mcp`; its tools are `papio_*` (see [MCP tools](" + llmsSiteURL + "reference/mcp-tools/)).\n")
	b.WriteString("4. Check integration readiness with `papio doctor` after setup or configuration changes.\n\n")
	b.WriteString("The complete documentation as one Markdown file: " + llmsSiteURL + "llms-full.txt\n\n")

	section := ""
	for _, page := range pages {
		if page.section != section {
			section = page.section
			b.WriteString("\n## " + section + "\n\n")
		}
		b.WriteString("- [" + page.title + "](" + page.url + ")")
		if page.desc != "" {
			b.WriteString(": " + page.desc)
		}
		b.WriteString("\n")
	}
	return b.String()
}

func renderLLMSFull(pages []llmsPage) string {
	var b strings.Builder
	b.WriteString("# papio — full documentation\n\n")
	b.WriteString("A local paper-acquisition broker. This file concatenates the complete docs as Markdown for AI agents. Source: " + llmsSiteURL + "\n")
	b.WriteString("For the token-efficient path, start with the getting-started guide, then `papio init`, `papio mcp`, and `papio doctor` rather than consuming this whole file.\n")
	for _, page := range pages {
		b.WriteString("\n\n---\n\n> Source: " + page.url + "\n\n")
		b.WriteString(page.body)
		b.WriteString("\n")
	}
	return b.String()
}
